services:
  db: 
    image: mariadb  # Použije předpřipravený obraz MariaDB (databáze) z Docker Hubu
    restart: always # Pokud kontejner spadne nebo se restartuje PC, automaticky se spustí znovu
    environment:    # Nastavení vnitřních proměnných pro databázi
      MYSQL_ROOT_PASSWORD: heslo 
      MYSQL_DATABASE: moje_databaze
      MYSQL_USER: student
      MYSQL_PASSWORD: heslo
    ports:
      - "3306:3306" # Propojení portů: vnitřní port databáze (3306) se namapuje na port 3306 v mém PC
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Při úplně prvním startu se automaticky spustí init.sql, který vytvoří tabulky

  web:
    image: php:8.2-apache # Obraz, který v sobě má PHP 8.2 a webový server Apache
    volumes:
      - .:/var/www/html     # Propojí aktuální složku v PC do složky serveru v Dockeru (změny v kódu se hned projeví na webu)
    ports:
      - "8080:80" # Webový server poslouchá uvnitř na portu 80, v prohlížeči přistoupím přes localhost:8080
    depends_on:
      - db # Zajistí, že se spustí mariadb jako první a poté na ní web. server počká 
    
    command: > # Příkaz, který uvnitř kontejneru doinstaluje rozšíření PDO pro PHP, aby se šlo vůbec spojit s Db 
      sh -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"
